### ISSUE TITLE
Build tool only

### ISSUE THREAD

**Issue by dschrempf** [danielfullmer/robotnix#154]
Hello!

Is it possible to build single components using `robotnix`? I would like to build `dicttool_aosp` only.

Thanks for your help!

**Comment by danielfullmer** [comment]
Indeed it is. Here's an example I had previously done for someone wanting to build the bionic libc:
https://gist.github.com/danielfullmer/5f959d8f42c7a916b597ab95d8a414a6
Run `nix-build` on this file at the root of the robotnix git checkout and it would output a built libc.  It does, however, still download a ton of unnecessary repositories for building bionic, since the android build system doesn't seem to work well on partial checkouts of the repo tree.

Currently, it requires knowing where the build system puts the output to know how to copy the relevant files in `installPhase`, but I have an idea that might work to make it even simpler: https://github.com/danielfullmer/robotnix/issues/155

**Comment by dschrempf** [comment]
Thank you!
