### ISSUE TITLE
OTA updates fail during reboot step

### ISSUE THREAD

**Issue by mgidding** [danielfullmer/robotnix#178]
Hello, I am new to robotnix and I'm trying to use the OTA updater for the first time. I have managed to make the updater download and apply an OTA update. However once I reboot my phone afterwards it will show the android logo for a few minutes, reboot again and then attempt to download the same update once more (without having updated my phone).

Bumping the version number (by changing buildDateTime) and building the OTA update again did not help.

**Comment by mgidding** [comment]
I have managed to make OTA updates work by removing the new prebuilt app I had included (with privileged = true;).

**Comment by zhaofengli** [comment]
You likely triggered the rollback mechanism because the new update failed to boot. For privileged apps, the system will simply refuse to boot if it's not allowed all privileged permissions that it's declared with (see [Privileged Application Allowlisting](https://source.android.com/devices/tech/config/perms-allowlist)).

**Comment by mgidding** [comment]
Thank you for the response! It seems that was indeed my issue.
