### ISSUE TITLE
Set APNs using carriersettings-extractor

### ISSUE THREAD

**Issue by danielfullmer** [danielfullmer/robotnix#20]
VoLTE doesn't work out of the box using a vanilla AOSP build. This project https://github.com/daradib/carriersettings-extractor extracts the APN/carrier settings from the `CarrierSettings` app included in Google's pixel images and generates configuration files that can be included in the AOSP build.

This generated configuration is now included in the latest GrapheneOS builds.  

A robotnix module could be made which would automatically extract these settings using the latest vendor image and include them in the build.  This should hopefully make VoLTE work for `vanilla` builds as well.

See also: https://github.com/GrapheneOS/os_issue_tracker/issues/153

**Comment by daradib** [comment]
Just to clarify, VoLTE should work out of the box in AOSP with supported carriers. Make sure org.codeaurora.ims is installed/enabled. The problem is that some carriers like Visible don't include their required settings in AOSP, perhaps so they can limit the devices that are supported. GrapheneOS bundles the APNs extracted from the protobuf files in the pixel images, which adds support for Visible.
